import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "./components/NavBar";
import PageLayout from "./components/PageLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar>
          <Link
            href="/"
            className="text-sm hover:opacity-70 transition-opacity"
          >
            Home
          </Link>
          <Link
            href="/chord-pairs"
            className="text-sm hover:opacity-70 transition-opacity"
          >
            Chord Pairs
          </Link>
        </NavBar>
        <PageLayout>
          {children}
        </PageLayout>
      </body>
    </html>
  );
}
