import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./Layout.css";
import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <div className="flex flex-col h-full">
          <NavBar>
            <Link
              href="/"
              className="text-sm hover:opacity-70 transition-opacity"
            >
              Home
            </Link>
            <Link
              href="/chord-pairs"
              className="text-sm hover:opacity-70 transition-opacity"
            >
              Chord Pairs
            </Link>
          </NavBar>
          <div className="p-4 h-full overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
